<?php

 $title = 'Add new user';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('user', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id_user'));
 echo $this->formRow($form->get('nom_user'));
 echo $this->formRow($form->get('prenom_user'));
 echo $this->formRow($form->get('mail_user'));
 echo $this->formRow($form->get('date_de_naissance_user'));
 echo $this->formRow($form->get('sexe_user'));
 echo $this->formRow($form->get('adresse_user'));
 echo $this->formRow($form->get('code_postal_user'));
 echo $this->formRow($form->get('ville_user'));
 echo $this->formRow($form->get('pays_user'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();