<?php

 $title = 'Supprimer mon Compte';
 $this->headTitle($title);
 ?>

 <?php
 $url = $this->url('user', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
     <fieldset>
         <legend><?php echo $this->escapeHtml($title); ?></legend>
 <div>
     <label>Êtes-vous sûr de vouloir supprimer définitivement votre compte ?</label><br>
     <input type="hidden" name="id" value="<?php echo (int) $user->id_user; ?>" />
     <input class="btn btn-success" type="submit" name="del" value="Oui" />
     <input class="btn btn-danger" type="submit" name="del" value="Non" />
 </div>
     </fieldset>
 </form>