<?php
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('action', $this->url('user', array('action' => 'login')));
$form->prepare();
?>
<?php if (isset($formenonvalide)){ 
     var_dump($formenonvalide);
            unset($formenonvalide);
}?>


<?php echo $this->form()->openTag($form); ?>
<fieldset>
    <legend><?php echo $this->escapeHtml($title); ?></legend>
<div class='row'>
    <div class='col-xs-6 col-xs-offset-3'>
        <div class="form-group">
            <label for="mail_user" class="control-label col-xs-4">Email</label>
            <div class="col-xs-8">
                <?php echo $this->formRow($form->get('mail_user')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="password_user" class="control-label col-xs-4">Password</label>
            <div class="col-xs-8">
                <?php echo $this->formRow($form->get('password_user')); ?>
            </div>
        </div>
    
    </div>
</div>
<div class="row">
        <div class="form-group">
            <div class="col-xs-offset-5">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>
</div>
    
    
</fieldset>
        <?php echo $this->form()->closeTag(); ?>

