<?php
$this->headTitle($title);
$form = $this->form;
$form->prepare();
$form->setAttribute('action', '/user/login');
$form->get('mail_user')->setAttribute('class', 'textbox');
$form->get('password_user')->setAttribute('class', 'textbox');
$form->get('submit')->setAttribute('class', 'button');
?>
           
<form class="form-horizontal">

<?php echo $this->form()->openTag($form); ?>
<fieldset>

<!-- Form Name -->
<legend>Login</legend>

<!-- Text input-->
<div class="control-group">
  <label class="control-label" for="mail_user">Mail</label>
  <div class="controls">
      <?php echo $this->formText($form->get('mail_user')); ?>
    
  </div>
</div>

<!-- Password input-->
<div class="control-group">
  <label class="control-label" for="password_user">Password</label>
  <div class="controls">
      
	<?php echo $this->formPassword($form->get('password_user')); ?>
    
  </div>
</div>

<?php echo $this->formElement($form->get('csrf')) ?>
<!-- Button -->
<div class="control-group">
  <label class="control-label" for="submit"></label>
  <div class="controls">
    <?php echo $this->formSubmit($form->get('submit')); ?>
  </div>
</div>

</fieldset>
    
<?php echo $this->form()->closeTag(); ?>
</form>

<br />
<?php if (isset($loginMsg[0])): ?>
	<span class="red"><?php echo $loginMsg[0]; ?></span><br />
<?php endif ?>

        
<!-- <style type="text/css">
  .fb-sign-in-button {
  	background:transparent url(/images/sign-in-with-facebook-twitter-button.jpg) 0 0 no-repeat;vertical-align:middle;display:-moz-inline-stack;display:inline-block;zoom:1;width:190px;height:35px;*display:inline;*margin:10px 20px 0 20px;background-position:-170px -110px; 
  }
 .tw-sign-in-button {
  	background:transparent url(/images/sign-in-with-facebook-twitter-button.jpg) 0 0 no-repeat;vertical-align:middle;display:-moz-inline-stack;display:inline-block;zoom:1;width:190px;height:35px;*display:inline;*margin:10px 20px 0 20px;background-position:-170px -157px; 
  }
}
</style> -->