<?php
use Zend\Session\Container;
$session = new Container('user');
if ($session->offsetExists('id_user')) {
    $id_user = $session->offsetGet('id_user');
}
$title = 'Ajouter un Post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('post', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_post'));
echo $this->formHidden($form->get('id_user')->setValue($id_user));
echo $this->formRow($form->get('titre'));
echo $this->formRow($form->get('contenu'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
