<?php

use Zend\Session\Container;

$session = new Container('socialnetwork_user');
$this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-select.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap-select.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>
        

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color: #4664a0" >
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php if ($session->offsetExists('id_user')) { ?>
                            <li><a style="color: white" href="<?php echo $this->url('post') ?>"><span class="glyphicon glyphicon-th-list"></span> Posts</a></li>
                            <li><a style="color: white" href="<?php echo $this->url('user') ?>"><span class="glyphicon glyphicon-user"></span> Utilisateurs</a></li>
                            <li><a style="color: white" href="<?php echo $this->url('user') . "logout" ?>"><span class="glyphicon glyphicon-log-out"></span> Deconnexion</a></li>
                        <?php } else { ?>
                            <li><a style="color: white" href="<?php echo $this->url('user') . "login" ?>"><span class="glyphicon glyphicon-log-in"></span> Connexion</a></li>
                            <li><a style="color: white" href="<?php echo $this->url('user') . "add" ?>"><span class="glyphicon glyphicon-registration-mark"></span> Inscription</a></li>
                        <?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <script type="text/javascript">
            $('.selectpicker').selectpicker({
                margin: 0,
                padding: 0,
                style: 'btn-info',
                size: 4
            });
        </script>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by Yann01240. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
